### ISSUE TITLE
Tympan Sound Level Meter Frequencies Shifted

### ISSUE THREAD

**Issue by BAyotte** [Tympan/Tympan_Sandbox#7]
@chipaudette 

Code here: https://github.com/Tympan/Tympan_Sandbox/tree/master/OpenHearing/SoundLevelMeterTabsint

In the function "printLoudnessLevels" the returned values appear to have their indexes shifted to the right by one. When we play a 1kHz tone the tympan thinks the sound is 2kHz, when we play 2kHz tone the tympan thinks the sound is 4kHz and so on.

**Comment by chipaudette** [comment]
I think that I fixed this bug.

It was a problem with how the center frequencies were being converted into cross-overfrequencies.   I had some off-by-one errors.

I've also added a lot more comments to this section of code describing how the filterbank class, in addition to creating the desired bandpass filters, also creates a lowpass and highpass filter.  Accounting for these extra filters is what makes the indexing weird, which is what caused my off-by-one type errors.

@BAyotte, as of commit 89c6c4a to the main branch of the repo, this should be fixed.  Or just update to the latest version of the repo, which is probably easier.

Let me know if it worked (or simply close the issue).
